---
- hosts: '*'
  vars:
    build_root: ..
    build_dir: '{{ build_root }}/_site'
    remote_dir: /home/hix_io/www
  tasks:
    - name: local clean
      shell: jekyll clean
      args: 
        removes: '{{ build_dir }}'
        chdir: '{{ build_root }}'
      delegate_to: localhost

    - name: local build
      shell: jekyll build
      args: 
        creates: '{{ build_dir }}'
        chdir: '{{ build_root }}'
      delegate_to: localhost

    - name: deploy
      synchronize: 
        src: '{{ build_dir }}/'
        dest: '{{ remote_dir }}'
        recursive: yes
        delete: yes
        archive: no
      vars:
        ansible_ssh_user: hix_io

